export interface Question {
  id: number;
  category: string;
  difficulty: "Easy" | "Medium" | "Hard";
  type: "multiple" | "boolean";
  question: string;
  options: string[];
  answer: number;
}

export const categories = [
  "General Knowledge",
  "Science & Nature",
  "History",
  "Technology",
  "Movies",
  "Sports",
  "Music",
  "Geography",
] as const;

export type Category = (typeof categories)[number];

export const questions: Question[] = [
  { id: 1, category: "General Knowledge", difficulty: "Easy", type: "multiple", question: "What is the capital of France?", options: ["London", "Berlin", "Paris", "Madrid"], answer: 2 },
  { id: 2, category: "General Knowledge", difficulty: "Easy", type: "multiple", question: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: 2 },
  { id: 3, category: "General Knowledge", difficulty: "Easy", type: "multiple", question: "What color are bananas when ripe?", options: ["Green", "Yellow", "Red", "Blue"], answer: 1 },
  { id: 4, category: "General Knowledge", difficulty: "Easy", type: "multiple", question: "How many sides does a triangle have?", options: ["2", "3", "4", "5"], answer: 1 },
  { id: 5, category: "General Knowledge", difficulty: "Easy", type: "multiple", question: "What is the opposite of hot?", options: ["Warm", "Cold", "Cool", "Mild"], answer: 1 },
  { id: 6, category: "General Knowledge", difficulty: "Easy", type: "boolean", question: "The Earth is flat.", options: ["True", "False"], answer: 1 },
  { id: 7, category: "General Knowledge", difficulty: "Easy", type: "boolean", question: "Water freezes at 0 degrees Celsius.", options: ["True", "False"], answer: 0 },
  { id: 8, category: "General Knowledge", difficulty: "Medium", type: "multiple", question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], answer: 1 },
  { id: 9, category: "General Knowledge", difficulty: "Medium", type: "multiple", question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: 3 },
  { id: 10, category: "General Knowledge", difficulty: "Medium", type: "multiple", question: "Who painted the Mona Lisa?", options: ["Michelangelo", "Da Vinci", "Raphael", "Van Gogh"], answer: 1 },
  { id: 11, category: "General Knowledge", difficulty: "Medium", type: "multiple", question: "What is the currency of Japan?", options: ["Yuan", "Won", "Yen", "Ringgit"], answer: 2 },
  { id: 12, category: "General Knowledge", difficulty: "Medium", type: "multiple", question: "How many continents are there?", options: ["5", "6", "7", "8"], answer: 2 },
  { id: 13, category: "General Knowledge", difficulty: "Medium", type: "boolean", question: "Australia is both a country and a continent.", options: ["True", "False"], answer: 0 },
  { id: 14, category: "General Knowledge", difficulty: "Hard", type: "multiple", question: "What is the smallest country in the world?", options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], answer: 2 },
  { id: 15, category: "General Knowledge", difficulty: "Hard", type: "multiple", question: "How many bones are in the adult human body?", options: ["186", "206", "226", "256"], answer: 1 },
  { id: 16, category: "General Knowledge", difficulty: "Hard", type: "multiple", question: "What year did the Titanic sink?", options: ["1905", "1912", "1918", "1923"], answer: 1 },
  { id: 17, category: "General Knowledge", difficulty: "Hard", type: "multiple", question: "What is the longest river in Europe?", options: ["Danube", "Rhine", "Volga", "Seine"], answer: 2 },
  { id: 18, category: "General Knowledge", difficulty: "Hard", type: "multiple", question: "Which language has the most native speakers?", options: ["English", "Hindi", "Mandarin Chinese", "Spanish"], answer: 2 },
  { id: 19, category: "General Knowledge", difficulty: "Hard", type: "boolean", question: "The Amazon is the longest river in the world.", options: ["True", "False"], answer: 1 },
  { id: 20, category: "General Knowledge", difficulty: "Easy", type: "boolean", question: "Humans have five senses.", options: ["True", "False"], answer: 0 },

  { id: 21, category: "Science & Nature", difficulty: "Easy", type: "multiple", question: "What gas do plants absorb from the air?", options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], answer: 2 },
  { id: 22, category: "Science & Nature", difficulty: "Easy", type: "multiple", question: "How many legs does a spider have?", options: ["6", "8", "10", "12"], answer: 1 },
  { id: 23, category: "Science & Nature", difficulty: "Easy", type: "multiple", question: "What is H2O commonly known as?", options: ["Salt", "Sugar", "Water", "Vinegar"], answer: 2 },
  { id: 24, category: "Science & Nature", difficulty: "Easy", type: "multiple", question: "What color is the sky on a clear day?", options: ["Green", "Red", "Blue", "Yellow"], answer: 2 },
  { id: 25, category: "Science & Nature", difficulty: "Easy", type: "multiple", question: "Which animal is known as man's best friend?", options: ["Cat", "Dog", "Fish", "Bird"], answer: 1 },
  { id: 26, category: "Science & Nature", difficulty: "Easy", type: "boolean", question: "The sun rises in the west.", options: ["True", "False"], answer: 1 },
  { id: 27, category: "Science & Nature", difficulty: "Easy", type: "boolean", question: "Fish can breathe underwater.", options: ["True", "False"], answer: 0 },
  { id: 28, category: "Science & Nature", difficulty: "Medium", type: "multiple", question: "What is the hardest natural substance?", options: ["Gold", "Iron", "Diamond", "Platinum"], answer: 2 },
  { id: 29, category: "Science & Nature", difficulty: "Medium", type: "multiple", question: "What organ pumps blood throughout the body?", options: ["Lungs", "Brain", "Heart", "Liver"], answer: 2 },
  { id: 30, category: "Science & Nature", difficulty: "Medium", type: "multiple", question: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Neptune", "Uranus"], answer: 1 },
  { id: 31, category: "Science & Nature", difficulty: "Medium", type: "multiple", question: "What type of blood cells fight infections?", options: ["Red", "White", "Platelets", "Plasma"], answer: 1 },
  { id: 32, category: "Science & Nature", difficulty: "Medium", type: "multiple", question: "How many teeth does an adult human have?", options: ["28", "30", "32", "34"], answer: 2 },
  { id: 33, category: "Science & Nature", difficulty: "Medium", type: "boolean", question: "The human body has 206 bones.", options: ["True", "False"], answer: 0 },
  { id: 34, category: "Science & Nature", difficulty: "Hard", type: "multiple", question: "What is the speed of light approximately?", options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "1,000,000 km/s"], answer: 0 },
  { id: 35, category: "Science & Nature", difficulty: "Hard", type: "multiple", question: "Which element has the highest melting point?", options: ["Iron", "Tungsten", "Platinum", "Titanium"], answer: 1 },
  { id: 36, category: "Science & Nature", difficulty: "Hard", type: "multiple", question: "What is the largest organ in the human body?", options: ["Liver", "Brain", "Skin", "Lungs"], answer: 2 },
  { id: 37, category: "Science & Nature", difficulty: "Hard", type: "multiple", question: "What is the atomic number of Carbon?", options: ["4", "6", "8", "10"], answer: 1 },
  { id: 38, category: "Science & Nature", difficulty: "Hard", type: "multiple", question: "Which gas makes up most of Earth's atmosphere?", options: ["Oxygen", "Nitrogen", "CO2", "Argon"], answer: 1 },
  { id: 39, category: "Science & Nature", difficulty: "Hard", type: "boolean", question: "Pluto is still classified as a planet.", options: ["True", "False"], answer: 1 },

  { id: 40, category: "History", difficulty: "Easy", type: "multiple", question: "Who discovered America in 1492?", options: ["Magellan", "Columbus", "Vasco da Gama", "Cook"], answer: 1 },
  { id: 41, category: "History", difficulty: "Easy", type: "multiple", question: "Which ancient civilization built the pyramids?", options: ["Romans", "Greeks", "Egyptians", "Persians"], answer: 2 },
  { id: 42, category: "History", difficulty: "Easy", type: "multiple", question: "The Great Wall of China was built to protect against what?", options: ["Floods", "Invasions", "Wild animals", "Storms"], answer: 1 },
  { id: 43, category: "History", difficulty: "Easy", type: "multiple", question: "Who was the first man to walk on the Moon?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], answer: 1 },
  { id: 44, category: "History", difficulty: "Easy", type: "multiple", question: "Which country invented paper?", options: ["India", "Egypt", "China", "Greece"], answer: 2 },
  { id: 45, category: "History", difficulty: "Easy", type: "boolean", question: "The Titanic sank in 1912.", options: ["True", "False"], answer: 0 },
  { id: 46, category: "History", difficulty: "Medium", type: "multiple", question: "In what year did World War II end?", options: ["1943", "1944", "1945", "1946"], answer: 2 },
  { id: 47, category: "History", difficulty: "Medium", type: "multiple", question: "Who was the first President of the United States?", options: ["Adams", "Jefferson", "Washington", "Lincoln"], answer: 2 },
  { id: 48, category: "History", difficulty: "Medium", type: "multiple", question: "The ancient city of Rome was built on how many hills?", options: ["Five", "Six", "Seven", "Eight"], answer: 2 },
  { id: 49, category: "History", difficulty: "Medium", type: "multiple", question: "Which empire was ruled by Genghis Khan?", options: ["Ottoman", "Roman", "Mongol", "Persian"], answer: 2 },
  { id: 50, category: "History", difficulty: "Medium", type: "multiple", question: "What was the name of the ship that brought the Pilgrims to America?", options: ["Santa Maria", "Mayflower", "Beagle", "Victoria"], answer: 1 },
  { id: 51, category: "History", difficulty: "Medium", type: "boolean", question: "The French Revolution started in 1789.", options: ["True", "False"], answer: 0 },
  { id: 52, category: "History", difficulty: "Hard", type: "multiple", question: "What was the longest war in history?", options: ["100 Years War", "30 Years War", "War of Roses", "Cold War"], answer: 0 },
  { id: 53, category: "History", difficulty: "Hard", type: "multiple", question: "Who was the last Pharaoh of Egypt?", options: ["Nefertiti", "Hatshepsut", "Cleopatra", "Ramesses"], answer: 2 },
  { id: 54, category: "History", difficulty: "Hard", type: "multiple", question: "The Rosetta Stone helped decipher which writing system?", options: ["Cuneiform", "Hieroglyphics", "Sanskrit", "Runes"], answer: 1 },
  { id: 55, category: "History", difficulty: "Hard", type: "multiple", question: "In which year did the Berlin Wall fall?", options: ["1987", "1988", "1989", "1990"], answer: 2 },
  { id: 56, category: "History", difficulty: "Hard", type: "multiple", question: "Who was the first female Prime Minister of a country?", options: ["Indira Gandhi", "Margaret Thatcher", "Golda Meir", "Sirimavo Bandaranaike"], answer: 3 },
  { id: 57, category: "History", difficulty: "Hard", type: "boolean", question: "The Cold War was fought between the USA and China.", options: ["True", "False"], answer: 1 },

  { id: 58, category: "Technology", difficulty: "Easy", type: "multiple", question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"], answer: 0 },
  { id: 59, category: "Technology", difficulty: "Easy", type: "multiple", question: "Who founded Microsoft?", options: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Jeff Bezos"], answer: 1 },
  { id: 60, category: "Technology", difficulty: "Easy", type: "multiple", question: "What does HTML stand for?", options: ["HyperText Markup Language", "HighTech Modern Language", "Home Tool Markup Language", "HyperTransfer Markup Language"], answer: 0 },
  { id: 61, category: "Technology", difficulty: "Easy", type: "multiple", question: "What does WiFi stand for?", options: ["Wireless Fidelity", "Wide Frequency", "Wireless Finder", "Web Fidelity"], answer: 0 },
  { id: 62, category: "Technology", difficulty: "Easy", type: "multiple", question: "Which company makes the iPhone?", options: ["Samsung", "Google", "Apple", "Microsoft"], answer: 2 },
  { id: 63, category: "Technology", difficulty: "Easy", type: "boolean", question: "The first computer virus was created in 1983.", options: ["True", "False"], answer: 0 },
  { id: 64, category: "Technology", difficulty: "Medium", type: "multiple", question: "What year was the iPhone first released?", options: ["2005", "2007", "2009", "2010"], answer: 1 },
  { id: 65, category: "Technology", difficulty: "Medium", type: "multiple", question: "What does SQL stand for?", options: ["Simple Query Language", "Structured Query Language", "Standard Query Logic", "Sequential Query Language"], answer: 1 },
  { id: 66, category: "Technology", difficulty: "Medium", type: "multiple", question: "Which company developed the Android OS?", options: ["Apple", "Microsoft", "Google", "Samsung"], answer: 2 },
  { id: 67, category: "Technology", difficulty: "Medium", type: "multiple", question: "What is the most used programming language?", options: ["Python", "JavaScript", "Java", "C++"], answer: 1 },
  { id: 68, category: "Technology", difficulty: "Medium", type: "multiple", question: "What does URL stand for?", options: ["Universal Resource Locator", "Uniform Resource Locator", "Unified Resource Link", "Universal Reference Link"], answer: 1 },
  { id: 69, category: "Technology", difficulty: "Medium", type: "boolean", question: "Python is a compiled language.", options: ["True", "False"], answer: 1 },
  { id: 70, category: "Technology", difficulty: "Hard", type: "multiple", question: "What language was created by Brendan Eich in 10 days?", options: ["Python", "Java", "JavaScript", "Ruby"], answer: 2 },
  { id: 71, category: "Technology", difficulty: "Hard", type: "multiple", question: "What does API stand for?", options: ["Application Programming Interface", "Automated Program Integration", "Advanced Platform Interface", "Application Process Integration"], answer: 0 },
  { id: 72, category: "Technology", difficulty: "Hard", type: "multiple", question: "What was the first commercially successful smartphone?", options: ["iPhone", "BlackBerry 850", "Nokia 9000", "Palm Treo"], answer: 2 },
  { id: 73, category: "Technology", difficulty: "Hard", type: "multiple", question: "What does SSD stand for?", options: ["Super Speed Drive", "Solid State Drive", "System Storage Device", "Sequential Storage Disk"], answer: 1 },
  { id: 74, category: "Technology", difficulty: "Hard", type: "multiple", question: "In what year was the World Wide Web invented?", options: ["1985", "1989", "1991", "1993"], answer: 1 },
  { id: 75, category: "Technology", difficulty: "Hard", type: "boolean", question: "JavaScript and Java are the same language.", options: ["True", "False"], answer: 1 },

  { id: 76, category: "Movies", difficulty: "Easy", type: "multiple", question: "Which movie features a character named Woody?", options: ["Frozen", "Toy Story", "Shrek", "Finding Nemo"], answer: 1 },
  { id: 77, category: "Movies", difficulty: "Easy", type: "multiple", question: "Who played Iron Man in the MCU?", options: ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], answer: 1 },
  { id: 78, category: "Movies", difficulty: "Easy", type: "multiple", question: "What is the highest-grossing film of all time?", options: ["Titanic", "Avatar", "Avengers: Endgame", "Star Wars"], answer: 1 },
  { id: 79, category: "Movies", difficulty: "Easy", type: "multiple", question: "Which animated movie is about a clownfish looking for his son?", options: ["Shark Tale", "Finding Nemo", "The Little Mermaid", "SpongeBob"], answer: 1 },
  { id: 80, category: "Movies", difficulty: "Easy", type: "multiple", question: "What is the name of the wizard boy in the famous book series?", options: ["Harry Potter", "Percy Jackson", "Tom Riddle", "Draco Malfoy"], answer: 0 },
  { id: 81, category: "Movies", difficulty: "Easy", type: "boolean", question: "The highest-grossing film of all time is Avatar.", options: ["True", "False"], answer: 0 },
  { id: 82, category: "Movies", difficulty: "Medium", type: "multiple", question: "What year was the first Harry Potter movie released?", options: ["1999", "2000", "2001", "2002"], answer: 2 },
  { id: 83, category: "Movies", difficulty: "Medium", type: "multiple", question: "Which director made Pulp Fiction?", options: ["Spielberg", "Tarantino", "Scorsese", "Nolan"], answer: 1 },
  { id: 84, category: "Movies", difficulty: "Medium", type: "multiple", question: "In The Matrix, what color pill does Neo take?", options: ["Blue", "Red", "Green", "Yellow"], answer: 1 },
  { id: 85, category: "Movies", difficulty: "Medium", type: "multiple", question: "Which movie won the Oscar for Best Picture in 2020?", options: ["1917", "Parasite", "Joker", "Once Upon a Time"], answer: 1 },
  { id: 86, category: "Movies", difficulty: "Medium", type: "multiple", question: "Who voiced Darth Vader in Star Wars?", options: ["James Earl Jones", "Morgan Freeman", "Liam Neeson", "Samuel L. Jackson"], answer: 0 },
  { id: 87, category: "Movies", difficulty: "Medium", type: "boolean", question: "The Dark Knight won an Oscar for Best Picture.", options: ["True", "False"], answer: 1 },
  { id: 88, category: "Movies", difficulty: "Hard", type: "multiple", question: "Which film won the first Academy Award for Best Picture?", options: ["Wings", "Sunrise", "The Broadway Melody", "Wings"], answer: 0 },
  { id: 89, category: "Movies", difficulty: "Hard", type: "multiple", question: "Who played the Joker in The Dark Knight?", options: ["Jack Nicholson", "Heath Ledger", "Joaquin Phoenix", "Jared Leto"], answer: 1 },
  { id: 90, category: "Movies", difficulty: "Hard", type: "multiple", question: "What was the first feature-length animated film?", options: ["Snow White", "Pinocchio", "Fantasia", "Bambi"], answer: 0 },
  { id: 91, category: "Movies", difficulty: "Hard", type: "multiple", question: "Which director made Schindler's List?", options: ["Steven Spielberg", "Martin Scorsese", "Ridley Scott", "James Cameron"], answer: 0 },
  { id: 92, category: "Movies", difficulty: "Hard", type: "boolean", question: "The first feature-length animated film was Snow White.", options: ["True", "False"], answer: 0 },

  { id: 93, category: "Sports", difficulty: "Easy", type: "multiple", question: "How many players are on a soccer team?", options: ["9", "10", "11", "12"], answer: 2 },
  { id: 94, category: "Sports", difficulty: "Easy", type: "multiple", question: "Which sport is played at Wimbledon?", options: ["Cricket", "Tennis", "Golf", "Baseball"], answer: 1 },
  { id: 95, category: "Sports", difficulty: "Easy", type: "multiple", question: "What color are Olympic gold medals?", options: ["Silver", "Gold", "Bronze", "Copper"], answer: 1 },
  { id: 96, category: "Sports", difficulty: "Easy", type: "multiple", question: "Which sport uses a bat and ball?", options: ["Tennis", "Baseball", "Golf", "Bowling"], answer: 1 },
  { id: 97, category: "Sports", difficulty: "Easy", type: "multiple", question: "How many points is a touchdown worth?", options: ["3", "5", "6", "7"], answer: 2 },
  { id: 98, category: "Sports", difficulty: "Easy", type: "boolean", question: "Soccer is also known as football in most countries.", options: ["True", "False"], answer: 0 },
  { id: 99, category: "Sports", difficulty: "Medium", type: "multiple", question: "Who holds the record for most home runs in MLB?", options: ["Babe Ruth", "Barry Bonds", "Hank Aaron", "Willie Mays"], answer: 1 },
  { id: 100, category: "Sports", difficulty: "Medium", type: "multiple", question: "In which sport is the term love used?", options: ["Badminton", "Tennis", "Cricket", "Squash"], answer: 1 },
  { id: 101, category: "Sports", difficulty: "Medium", type: "multiple", question: "How often is the FIFA World Cup held?", options: ["2 years", "3 years", "4 years", "5 years"], answer: 2 },
  { id: 102, category: "Sports", difficulty: "Medium", type: "multiple", question: "Which country has won the most FIFA World Cups?", options: ["Germany", "Argentina", "Brazil", "Italy"], answer: 2 },
  { id: 103, category: "Sports", difficulty: "Medium", type: "multiple", question: "What sport does LeBron James play?", options: ["Football", "Basketball", "Baseball", "Soccer"], answer: 1 },
  { id: 104, category: "Sports", difficulty: "Medium", type: "boolean", question: "Brazil has won the FIFA World Cup 5 times.", options: ["True", "False"], answer: 0 },
  { id: 105, category: "Sports", difficulty: "Hard", type: "multiple", question: "Which country invented cricket?", options: ["Australia", "India", "England", "South Africa"], answer: 2 },
  { id: 106, category: "Sports", difficulty: "Hard", type: "multiple", question: "Who has the most Olympic gold medals?", options: ["Usain Bolt", "Michael Phelps", "Carl Lewis", "Mark Spitz"], answer: 1 },
  { id: 107, category: "Sports", difficulty: "Hard", type: "multiple", question: "What is the diameter of a basketball hoop in inches?", options: ["16", "18", "20", "22"], answer: 1 },
  { id: 108, category: "Sports", difficulty: "Hard", type: "multiple", question: "Which Grand Slam is played on clay?", options: ["Wimbledon", "US Open", "French Open", "Australian Open"], answer: 2 },
  { id: 109, category: "Sports", difficulty: "Hard", type: "boolean", question: "Michael Phelps has the most Olympic gold medals.", options: ["True", "False"], answer: 0 },

  { id: 110, category: "Music", difficulty: "Easy", type: "multiple", question: "Which instrument has 88 keys?", options: ["Guitar", "Violin", "Piano", "Flute"], answer: 2 },
  { id: 111, category: "Music", difficulty: "Easy", type: "multiple", question: "Who is known as the King of Pop?", options: ["Elvis Presley", "Michael Jackson", "Prince", "Madonna"], answer: 1 },
  { id: 112, category: "Music", difficulty: "Easy", type: "multiple", question: "Which band performed Yellow Submarine?", options: ["Rolling Stones", "Queen", "The Beatles", "Pink Floyd"], answer: 2 },
  { id: 113, category: "Music", difficulty: "Easy", type: "multiple", question: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], answer: 2 },
  { id: 114, category: "Music", difficulty: "Easy", type: "multiple", question: "Which singer is known as the Queen of Pop?", options: ["Beyoncé", "Madonna", "Lady Gaga", "Taylor Swift"], answer: 1 },
  { id: 115, category: "Music", difficulty: "Easy", type: "boolean", question: "Beethoven was deaf.", options: ["True", "False"], answer: 0 },
  { id: 116, category: "Music", difficulty: "Medium", type: "multiple", question: "What music genre originated in New Orleans?", options: ["Rock", "Jazz", "Blues", "Country"], answer: 1 },
  { id: 117, category: "Music", difficulty: "Medium", type: "multiple", question: "Which composer was deaf?", options: ["Mozart", "Bach", "Beethoven", "Chopin"], answer: 2 },
  { id: 118, category: "Music", difficulty: "Medium", type: "multiple", question: "What instrument does Yo-Yo Ma play?", options: ["Violin", "Cello", "Viola", "Bass"], answer: 1 },
  { id: 119, category: "Music", difficulty: "Medium", type: "multiple", question: "Which band released Abbey Road?", options: ["The Rolling Stones", "The Beatles", "Led Zeppelin", "Queen"], answer: 1 },
  { id: 120, category: "Music", difficulty: "Medium", type: "multiple", question: "What genre is Taylor Swift known for?", options: ["Rock", "Pop", "Country", "Hip Hop"], answer: 2 },
  { id: 121, category: "Music", difficulty: "Medium", type: "boolean", question: "The Beatles have more #1 hits than any other band.", options: ["True", "False"], answer: 0 },
  { id: 122, category: "Music", difficulty: "Hard", type: "multiple", question: "How many symphonies did Beethoven compose?", options: ["7", "9", "11", "13"], answer: 1 },
  { id: 123, category: "Music", difficulty: "Hard", type: "multiple", question: "Which year was the first Grammy Awards held?", options: ["1957", "1959", "1961", "1963"], answer: 1 },
  { id: 124, category: "Music", difficulty: "Hard", type: "multiple", question: "What is the highest female singing voice?", options: ["Alto", "Mezzo-soprano", "Soprano", "Contralto"], answer: 2 },
  { id: 125, category: "Music", difficulty: "Hard", type: "multiple", question: "What was Elvis Presley's first hit single?", options: ["Hound Dog", "Heartbreak Hotel", "Jailhouse Rock", "Love Me Tender"], answer: 1 },
  { id: 126, category: "Music", difficulty: "Hard", type: "boolean", question: "The Grammy Awards started in 1959.", options: ["True", "False"], answer: 0 },

  { id: 127, category: "Geography", difficulty: "Easy", type: "multiple", question: "What is the longest river in the world?", options: ["Amazon", "Nile", "Mississippi", "Yangtze"], answer: 1 },
  { id: 128, category: "Geography", difficulty: "Easy", type: "multiple", question: "Which country has the largest population?", options: ["USA", "India", "China", "Indonesia"], answer: 1 },
  { id: 129, category: "Geography", difficulty: "Easy", type: "multiple", question: "What is the largest continent?", options: ["Africa", "North America", "Asia", "Europe"], answer: 2 },
  { id: 130, category: "Geography", difficulty: "Easy", type: "multiple", question: "What is the tallest mountain in the world?", options: ["K2", "Everest", "Denali", "Kilimanjaro"], answer: 1 },
  { id: 131, category: "Geography", difficulty: "Easy", type: "multiple", question: "Which country is in both Europe and Asia?", options: ["Greece", "Turkey", "Egypt", "Iran"], answer: 1 },
  { id: 132, category: "Geography", difficulty: "Easy", type: "boolean", question: "Mount Everest is the tallest mountain in the world.", options: ["True", "False"], answer: 0 },
  { id: 133, category: "Geography", difficulty: "Medium", type: "multiple", question: "Which desert is the largest hot desert?", options: ["Gobi", "Kalahari", "Sahara", "Arabian"], answer: 2 },
  { id: 134, category: "Geography", difficulty: "Medium", type: "multiple", question: "How many countries border Brazil?", options: ["8", "9", "10", "11"], answer: 2 },
  { id: 135, category: "Geography", difficulty: "Medium", type: "multiple", question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Perth"], answer: 2 },
  { id: 136, category: "Geography", difficulty: "Medium", type: "multiple", question: "Which country has the most islands?", options: ["Indonesia", "Sweden", "Philippines", "Norway"], answer: 1 },
  { id: 137, category: "Geography", difficulty: "Medium", type: "multiple", question: "What is the smallest continent?", options: ["Europe", "Australia", "Antarctica", "South America"], answer: 1 },
  { id: 138, category: "Geography", difficulty: "Medium", type: "boolean", question: "Russia spans 11 time zones.", options: ["True", "False"], answer: 0 },
  { id: 139, category: "Geography", difficulty: "Hard", type: "multiple", question: "Which country has the most time zones?", options: ["USA", "Russia", "France", "China"], answer: 2 },
  { id: 140, category: "Geography", difficulty: "Hard", type: "multiple", question: "What is the deepest point in the ocean?", options: ["Mariana Trench", "Tonga Trench", "Puerto Rico Trench", "Java Trench"], answer: 0 },
  { id: 141, category: "Geography", difficulty: "Hard", type: "multiple", question: "Which lake is the largest by surface area?", options: ["Lake Superior", "Caspian Sea", "Lake Victoria", "Lake Baikal"], answer: 1 },
  { id: 142, category: "Geography", difficulty: "Hard", type: "multiple", question: "What is the driest inhabited continent?", options: ["Africa", "Australia", "Antarctica", "Asia"], answer: 1 },
  { id: 143, category: "Geography", difficulty: "Hard", type: "multiple", question: "Which strait separates Asia from North America?", options: ["Bosphorus", "Gibraltar", "Bering", "Malacca"], answer: 2 },
  { id: 144, category: "Geography", difficulty: "Hard", type: "boolean", question: "The Sahara is the largest hot desert in the world.", options: ["True", "False"], answer: 0 },
  { id: 145, category: "Geography", difficulty: "Easy", type: "multiple", question: "What is the capital of Egypt?", options: ["Cairo", "Alexandria", "Luxor", "Giza"], answer: 0 },
];
